### ISSUE TITLE
Nested containers are not disposed

### ISSUE THREAD

**Issue by mikeobrien** [WebApiContrib/WebApiContrib.IoC.StructureMap#7]
Would you be open to a PR that disposed the nested container?

**Comment by ivanmartinvalle** [comment]
@mikeobrien Why did you close this? We were sort of wondering the same thing...

**Comment by mikeobrien** [comment]
Found another solution and it looked like this repo wasn't very active.

**Comment by ivanmartinvalle** [comment]
@mikeobrien Thank you for your response!

What was your solution? I'm still trying to get a firm handle on how nested containers should work with Web API.

**Comment by mikeobrien** [comment]
I just ended up [writing my own](https://github.com/mikeobrien/WebApi.StructureMap). There is another one out there too (Can't remember the name ATM) but because of the absolutely _HORRIBLE_ "relevance" search on the Nuget gallery I missed it and wrote yet another one when an existing one might have been fine. ಠ_ಠ Anyways, there's a couple of more options out there.
